// The default capability matrix — an HONEST assessment of JATA Qi as of this
// build. Statuses are backed by the real, tested packages in this repo. The
// platform is explicitly NOT production-ready: many domain, commercial and
// governance capabilities are PLANNED or NOT_IMPLEMENTED.

import type { Capability } from './types.js';

const now = Date.now();
function cap(c: Omit<Capability, 'updatedAt'>): Capability {
  return { ...c, updatedAt: now };
}

export const DEFAULT_CAPABILITIES: Capability[] = [
  // --- Foundation (P0) ---
  cap({ id: 'kernel', name: 'Core Kernel (event bus, DI, lifecycle, config, logging)', category: 'foundation', status: 'TESTED', module: '@jataqi/core-kernel', evidence: ['20 unit tests', 'topological module lifecycle'] }),
  cap({ id: 'storage', name: 'Data Fabric (KV/collections/blobs, memory + filesystem)', category: 'foundation', status: 'TESTED', module: '@jataqi/storage', evidence: ['14 tests', 'pluggable drivers'] }),
  cap({ id: 'vector-search', name: 'Vector retrieval (embeddings + index)', category: 'foundation', status: 'TESTED', module: '@jataqi/vector-search', evidence: ['18 tests'] }),
  cap({ id: 'identity', name: 'Identity & Authentication (users, scrypt, sessions, API keys)', category: 'foundation', status: 'TESTED', module: '@jataqi/security', evidence: ['14 tests', 'bearer auth over HTTP'] }),
  cap({ id: 'security.rbac', name: 'RBAC authorization + permission enforcement', category: 'foundation', status: 'TESTED', module: '@jataqi/security', evidence: ['wildcard RBAC', 'gateway enforcement'] }),
  cap({ id: 'security.audit', name: 'Immutable audit ledger', category: 'foundation', status: 'TESTED', module: '@jataqi/security', evidence: ['append-only ledger', 'workflow attribution'] }),
  cap({ id: 'api', name: 'HTTP API gateway (auth, rate limiting, OpenAPI)', category: 'foundation', status: 'TESTED', module: '@jataqi/api-gateway', evidence: ['/openapi.json', 'rate limiting', '20+ endpoints'] }),
  cap({ id: 'observability', name: 'Observability (metrics, audit, structured logs)', category: 'foundation', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/metrics', notes: 'counters/gauges/histograms + Prometheus; no distributed tracing or dashboards yet' }),
  cap({ id: 'mfa-sso', name: 'MFA (TOTP RFC 6238) + session elevation', category: 'foundation', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/mfa', evidence: ['TOTP enrollment + verification (RFC 6238), backup codes, trusted devices, brute-force lockout, session elevation, 16 tests'], notes: 'no SSO/OAuth/OIDC integration yet; no SAML; no WebAuthn' }),
  cap({ id: 'multi-tenancy', name: 'Multi-tenancy & organizations (tenant isolation)', category: 'foundation', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/organizations', evidence: ['organizations, memberships, roles, invitations, role gating — 8 tests'], notes: 'org/membership model + per-org scoping helpers exist; full platform-wide tenant isolation on every store is not yet enforced everywhere' }),
  cap({ id: 'module-registry', name: 'Universal module registry', category: 'foundation', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/plugins', notes: 'plugin registry exists; formal module manifest registry PLANNED' }),

  // --- Intelligence (P1) ---
  cap({ id: 'qil', name: 'QiL orchestration language (lexer/parser/compiler)', category: 'intelligence', status: 'TESTED', module: '@jataqi/qil', evidence: ['19 tests', 'execution-plan DAG'] }),
  cap({ id: 'memory', name: 'Agent & session memory', category: 'intelligence', status: 'TESTED', module: '@jataqi/agent-runtime', evidence: ['ConversationManager', 'session memory'] }),
  cap({ id: 'knowledge', name: 'Knowledge fabric (ingest/chunk/retrieve/graph)', category: 'intelligence', status: 'TESTED', module: '@jataqi/knowledge-service', evidence: ['33 tests across knowledge + graph'] }),
  cap({ id: 'agents', name: 'Agent runtime (ReAct loop, tools, LLMs)', category: 'intelligence', status: 'TESTED', module: '@jataqi/agent-runtime', evidence: ['10 tests', 'Echo/Scripted/OpenAI LLMs'] }),
  cap({ id: 'workflows', name: 'Workflow engine (QiL plan execution, durable history)', category: 'intelligence', status: 'TESTED', module: '@jataqi/orchestrator', evidence: ['8 tests', 'durable run store'] }),
  cap({ id: 'model-abstraction', name: 'Model abstraction & routing', category: 'intelligence', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/model-registry', notes: 'catalog + selector implemented; not yet auto-wired into agent LLM choice at runtime' }),
  cap({ id: 'teams', name: 'Multi-agent orchestration (parallel/sequential/consensus)', category: 'intelligence', status: 'TESTED', module: '@jataqi/teams', evidence: ['5 tests'] }),
  cap({ id: 'tool-intelligence', name: 'Universal AI Tool Intelligence Layer', category: 'intelligence', status: 'TESTED', module: '@jataqi/tool-intelligence', evidence: ['registry, adapters, risk gating, fallback, approvals — 8 tests'] }),
  cap({ id: 'compute', name: 'Scientific/math compute (stats, regression, optimization)', category: 'intelligence', status: 'TESTED', module: '@jataqi/compute', evidence: ['11 tests', 'agent tools'] }),
  cap({ id: 'simulation', name: 'Simulation engine (Monte-Carlo)', category: 'intelligence', status: 'TESTED', module: '@jataqi/simulation', evidence: ['7 tests', 'probabilistic outputs'] }),
  cap({ id: 'scheduler', name: 'Compute scheduler + adaptive router', category: 'intelligence', status: 'TESTED', module: '@jataqi/scheduler', evidence: ['priority queue, targets, profile router'] }),

  // --- Developer (P2) ---
  cap({ id: 'cli', name: 'Developer CLI', category: 'developer', status: 'TESTED', module: '@jataqi/cli', evidence: ['serve, ask, models, simulate, plugins'] }),
  cap({ id: 'sdk', name: 'SDKs (Python/TS)', category: 'developer', status: 'NOT_IMPLEMENTED', notes: 'TypeScript library API only; no published SDKs' }),
  cap({ id: 'evals', name: 'AI evaluation platform (suites, metrics, regression)', category: 'developer', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/evals', evidence: ['eval suites, built-in metrics (exact/contains/token-overlap/regex), run scoring, regression comparison — 7 tests'], notes: 'no bias/safety/hallucination-specific evaluators yet; no scheduled evals; no dashboard' }),
  cap({ id: 'web-ui', name: 'Web/mobile dashboards & consoles', category: 'developer', status: 'NOT_IMPLEMENTED', notes: 'HTTP API only; no UI' }),

  // --- Commercial (P3) ---
  cap({ id: 'commerce', name: 'Commercial & product packaging engine (plans, subscriptions, entitlements, usage, credits, invoices, marketplace commissions)', category: 'commercial', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/commerce', evidence: ['configurable catalogue/plans/editions', 'subscription + trial lifecycle', 'quota enforcement', 'credits', 'invoices/tax/discount', 'marketplace commission split', 'analytics — 12 tests'], notes: 'engine is real & tested; payments are ABSTRACTED (no real provider wired, no real money movement); no customer billing portal UI; no dunning/tax-jurisdiction DB' }),
  cap({ id: 'marketplace', name: 'Marketplace storefront & seller economy', category: 'commercial', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/commerce', notes: 'purchase + commission + payout ledger implemented; no storefront UI, discovery, ratings, or real payouts' }),
  cap({ id: 'organizations', name: 'Organizations & teams', category: 'commercial', status: 'NOT_IMPLEMENTED' }),

  // --- Enterprise (P4) ---
  cap({ id: 'enterprise', name: 'Enterprise OS (CRM/ERP/HR/Finance/Procurement)', category: 'enterprise', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/enterprise', evidence: ['org units, records with typed data, workflows — 4 tests'], notes: 'no real CRM/ERP integrations; no multi-tenant data isolation enforcement' }),
  cap({ id: 'finance', name: 'Financial intelligence (wallets, ledgers, transactions, reconciliation)', category: 'enterprise', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/finance', evidence: ['immutable append-only ledger, wallets, credit/debit/transfer/reverse, reconciliation, governance-gated — 12 tests'], notes: 'real ledger engine; no real payment provider integration; no FX/multi-currency conversion; no regulated financial services' }),
  cap({ id: 'supply-chain', name: 'Supply chain intelligence (suppliers, inventory, POs, deliveries)', category: 'enterprise', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/supply-chain', evidence: ['suppliers+ratings, inventory with low-stock alerts, purchase orders with approval, deliveries with auto-stock-in — 3 tests'], notes: 'no demand forecasting, no logistics optimization, no multi-warehouse' }),

  // --- Domain intelligence (P5) ---
  cap({ id: 'education', name: 'Education intelligence (courses, lessons, enrollments, progress, student privacy)', category: 'domain', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/education', evidence: ['courses with levels, lessons, enrollments, progress tracking with completion, auto-complete at 100% — 7 tests'], notes: 'no AI tutors, no assessment grading, no institutional dashboards' }),
  cap({ id: 'health', name: 'Health intelligence (records, vitals, education — NOT a diagnostic tool)', category: 'domain', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/health', evidence: ['health records (restricted sensitivity), vital signs tracking, educational content with disclaimer, consent gate — 6 tests'], notes: 'information management ONLY; explicitly does NOT diagnose or prescribe; no clinical validation; consent enforced via privacy module when present' }),
  cap({ id: 'research', name: 'Research & scientific discovery (workspaces, experiments, literature, hypotheses)', category: 'domain', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/research', evidence: ['projects, experiments with status/results, literature refs with tags, hypothesis tracking (AI-flagged) — 7 tests'], notes: 'no literature search/PDF parsing; no reproducibility tracking automation; no collaboration features' }),
  cap({ id: 'communication', name: 'Communication intelligence (email/SMS/messaging adapters, templates)', category: 'domain', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/communication', evidence: ['adapter-based channels (email/sms/push/whatsapp/inapp), template interpolation, message log — 8 tests'], notes: 'no real email/SMS providers wired (adapter abstraction); no consent/anti-spam enforcement' }),
  cap({ id: 'multimedia', name: 'Multimedia Intelligence Suite (music, story, image, video, film)', category: 'domain', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/multimedia', evidence: ['projects, creative jobs, async rendering queue, versioned assets, licensing/watermark/provenance, voice-clone consent, governance gate, marketplace publish — 13 tests'], notes: 'text-based creative output (lyrics/story/screenplay) works end-to-end; audio/video/image synthesis requires external Renderer adapters (none wired by default — abstraction only)' }),
  cap({ id: 'creative', name: 'Creative intelligence (image/video/audio gen)', category: 'domain', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/multimedia', notes: 'rendering pipeline + asset model implemented; no live generative model providers connected' }),
  cap({ id: 'multimodal', name: 'Multimodal (vision/audio/video) models', category: 'domain', status: 'NOT_IMPLEMENTED', notes: 'model-registry catalogs capabilities; no live multimodal backends' }),

  // --- Physical / infrastructure (P6) ---
  cap({ id: 'robotics', name: 'Robotics & device registry', category: 'physical', status: 'TESTED', module: '@jataqi/robotics', notes: 'device/mission/telemetry abstraction; no real hardware connected' }),
  cap({ id: 'digital-twin', name: 'Digital twin framework', category: 'physical', status: 'TESTED', module: '@jataqi/digital-twin', evidence: ['7 tests', 'step/project'] }),
  cap({ id: 'iot', name: 'IoT (device registry, telemetry, commands)', category: 'physical', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/iot', evidence: ['devices, telemetry, commands with ack, offline detection — 5 tests'], notes: 'no real sensor/actuator hardware; abstract device protocol' }),
  cap({ id: 'cloud-devops', name: 'Cloud & DevOps (deployments, resources, logs, rollback)', category: 'physical', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/cloud-devops', evidence: ['deployment lifecycle (plan→deploy→rollback), infra resources, deployment logs — 5 tests'], notes: 'no real K8s/Docker integration; simulated deployment completion' }),
  cap({ id: 'smart-cities', name: 'Smart cities (services, metrics, threshold alerts)', category: 'physical', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/smart-cities', evidence: ['city services, metrics with threshold alerts, sustainability tracking — 3 tests'], notes: 'no real city infrastructure integration' }),
  cap({ id: 'environment', name: 'Environmental intelligence (monitoring, alerts, sustainability)', category: 'physical', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/environment', evidence: ['monitoring stations, readings with threshold alerts (severity-scaled), sustainability metrics — 4 tests'], notes: 'no real sensor integration, no satellite data, no climate modeling' }),

  // --- Governance & safety ---
  cap({ id: 'notifications', name: 'Notification engine (in-app, webhook, preferences, rate limits)', category: 'foundation', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/notifications', evidence: ['multi-channel delivery, inbox, preferences, rate limits, event-driven — 6 tests'], notes: 'email/SMS are adapter abstractions (no real provider wired); no portal UI' }),
  cap({ id: 'governance', name: 'Policy & compliance registry', category: 'governance', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/policies', evidence: ['declarative policy engine (allow/deny/require_approval)', 'compliance control registry + framework summary', '8 tests'], notes: 'engine + controls real; not yet wired as a mandatory gate on every action across all modules' }),
  cap({ id: 'policy-governance', name: 'Policy & governance control plane (versioned, tenant-aware, precedence, agent/tool governance)', category: 'governance', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/policy-governance', evidence: ['rich versioned policy model + multi-effect engine', 'precedence (deny>safety>legal>org>role>entitlement; sensitive default-deny)', 'MANDATORY pre-execution gate wired into orchestrator (every step) + tool-intelligence (every invoke)', 'org/role/entitlement integration, simulation, overrides, autonomy levels, agent governance', 'observability: per-decision metrics counter + durationMs + evaluation history trace', 'integration tests prove deny/require-approval block runtime actions'], notes: 'engine + registry + mandatory enforcement real & tested; no admin UI; conditions DSL intentionally small' }),
  cap({ id: 'feature-flags', name: 'Feature flags (deployment rollout, separate from entitlements)', category: 'foundation', status: 'TESTED', module: '@jataqi/feature-flags', evidence: ['deterministic % rollout, set/check — 4 tests'] }),
  cap({ id: 'data-privacy', name: 'Data privacy (classification, retention, consent, SARs)', category: 'governance', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/privacy', evidence: ['classification + AI-restriction check, retention, consent, subject-access requests — 4 tests'], notes: 'primitives real; not yet enforced platform-wide on every store or AI context path' }),
  cap({ id: 'human-oversight', name: 'Human approval engine (high-risk actions)', category: 'governance', status: 'TESTED', module: '@jataqi/tool-intelligence', evidence: ['approval gating for R4/R5 tools'] }),
  cap({ id: 'provenance', name: 'Creator identity & cryptographic provenance (JQ-CIP)', category: 'governance', status: 'TESTED', module: '@jataqi/provenance', evidence: ['Ed25519 signed root manifest', 'append-only hash-chained ledger', 'tamper detection', 'key rotation/revocation'], notes: 'creator = GITANYA K; private signing key kept out of the repo' }),
  cap({ id: 'ai-safety', name: 'AI safety framework (injection defenses, loop limits)', category: 'governance', status: 'PARTIALLY_IMPLEMENTED', notes: 'agent max-iterations + tool risk gating; no prompt-injection scanner' }),
  cap({ id: 'cyberdefense', name: 'Cybersecurity & threat defense (indicators, vulnerabilities, incidents)', category: 'governance', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/cyberdefense', evidence: ['threat indicators with value-checking, vulnerability lifecycle (open→remediated), incident management (open→resolved), security event log — 4 tests'], notes: 'no real SIEM integration, no automated remediation, no SOC dashboard' }),

  // --- Global / sovereign (P7) ---
  cap({ id: 'sovereign', name: 'Sovereign / government deployment', category: 'global', status: 'NOT_IMPLEMENTED' }),
  cap({ id: 'localization', name: 'Localization (locales, currencies, translations)', category: 'global', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/localization', evidence: ['locales, currencies, translation CRUD with variable interpolation, money formatting — 5 tests'], notes: 'no ICU/CLDR integration; no RTL rendering' }),
  cap({ id: 'disaster-recovery', name: 'Disaster recovery (snapshots, restore, verification)', category: 'global', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/disaster-recovery', evidence: ['point-in-time snapshots of storage namespaces, restore with hash verification, retention — 4 tests'], notes: 'no automated scheduling, no cross-region replication, no streaming backup' }),

  // --- Frontier (P8) — research/simulation only ---
  cap({ id: 'quantum', name: 'Quantum computing integration', category: 'frontier', status: 'RESEARCH_ONLY', notes: 'scheduler models a quantum target tag; no real quantum hardware' }),
  cap({ id: 'space', name: 'Space / interplanetary intelligence', category: 'frontier', status: 'RESEARCH_ONLY' }),
  cap({ id: 'self-evolution', name: 'Self-evolution engine (observation, analysis, proposals, experiments, governed autonomous optimization)', category: 'frontier', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/self-evolution', evidence: ['observation engine, analysis, proposal planner, experiment engine (AB/canary/shadow/sim), governance approval gate, rollback, lessons learned, explainability, cycle cap safety — 16 tests'], notes: 'no production code modification (proposals only); no real A/B infrastructure; no live model retraining; cycle-capped + human-governed' }),
];
