// The default capability matrix — an HONEST assessment of JATA Qi as of this
// build. Statuses are backed by the real, tested packages in this repo. The
// platform is explicitly NOT production-ready: many domain, commercial and
// governance capabilities are PLANNED or NOT_IMPLEMENTED.

import type { Capability } from './types.js';

const now = Date.now();
function cap(c: Omit<Capability, 'updatedAt'>): Capability {
  return { ...c, updatedAt: now };
}

export const DEFAULT_CAPABILITIES: Capability[] = [
  // --- Foundation (P0) ---
  cap({ id: 'kernel', name: 'Core Kernel (event bus, DI, lifecycle, config, logging)', category: 'foundation', status: 'TESTED', module: '@jataqi/core-kernel', evidence: ['20 unit tests', 'topological module lifecycle'] }),
  cap({ id: 'storage', name: 'Data Fabric (KV/collections/blobs, memory + filesystem + sqlite)', category: 'foundation', status: 'TESTED', module: '@jataqi/storage', evidence: ['pluggable drivers (memory/filesystem/sqlite)', 'tenant-scoped isolation (PR4)', 'encryption-at-rest + quota decorators (PR7)'] }),
  cap({ id: 'storage.encryption', name: 'Encryption at rest (AES-256-GCM, transparent driver decorator)', category: 'foundation', status: 'TESTED', module: '@jataqi/storage', evidence: ['EncryptedDriver wraps any driver; namespaces/collections/blobs sealed with random-nonce GCM', 'tamper detection + wrong-key rejection', 'session tokens stored under SHA-256 digest (not as plaintext key)', 'persistence of ciphertext across restarts; resilient to key mismatch (no boot crash)', 'env: STORAGE_ENCRYPTION_KEY', 'tests: encryption(8) + hardened-driver(11) + storage-hardening(3) + encrypted-sessions(2)'] }),
  cap({ id: 'storage.quotas', name: 'Storage quotas / size limits (per-namespace/collection byte caps)', category: 'foundation', status: 'TESTED', module: '@jataqi/storage', evidence: ['QuotaDriver enforces logical-byte quotas with lazy size accounting across restarts', 'over-quota writes throw QuotaExceededError; updates/deletes reconcile correctly', 'composes with encryption: QuotaDriver(EncryptedDriver(base))', 'env: STORAGE_DEFAULT_QUOTA_BYTES / STORAGE_QUOTAS'] }),
  cap({ id: 'storage.postgres', name: 'PostgreSQL networked driver (multi-writer horizontal scaling)', category: 'foundation', status: 'TESTED', module: '@jataqi/storage', evidence: ['pure-Node PostgreSQL v3 wire client (node:net + node:crypto) — zero deps', 'auth: trust / cleartext / md5 / SCRAM-SHA-256 (RFC 5802) + optional TLS upgrade', 'extended-query protocol (Parse/Bind/Describe/Execute/Sync) with serialized concurrency', 'PostgresDriver mirrors the SQLite schema over shared Postgres -> ACID multi-writer scale-out', '22 tests: codec(7) + auth/SCRAM(5) + end-to-end driver + multi-writer visibility against a pure-Node mock server + StorageModule wiring', 'env: STORAGE_DRIVER=postgres + PGHOST/PGPORT/PGUSER/PGPASSWORD/PGDATABASE/PGSSLMODE'] }),
  cap({ id: 'vector-search', name: 'Vector retrieval (embeddings + index)', category: 'foundation', status: 'TESTED', module: '@jataqi/vector-search', evidence: ['18 tests'] }),
  cap({ id: 'identity', name: 'Identity & Authentication (users, scrypt, sessions, API keys)', category: 'foundation', status: 'TESTED', module: '@jataqi/security', evidence: ['scrypt password hashing', 'bearer auth over HTTP', 'restart-safe persisted sessions (PR4) — survive kernel restart on durable drivers', 'session revoke/list/prune APIs + remote-address forensics'] }),
  cap({ id: 'security.sessions', name: 'Restart-safe session persistence (SQLite/filesystem)', category: 'foundation', status: 'TESTED', module: '@jataqi/security', evidence: ['sessions persisted to security.sessions collection; cache + throttled lastUsedAt flush', '9 tests: token survives restart, logout invalidates across restart, expiry pruned on boot, revoke/list', 'opt-out via persistSessions:false'] }),
  cap({ id: 'security.rbac', name: 'RBAC authorization + permission enforcement', category: 'foundation', status: 'TESTED', module: '@jataqi/security', evidence: ['wildcard RBAC', 'gateway enforcement'] }),
  cap({ id: 'security.audit', name: 'Immutable audit ledger', category: 'foundation', status: 'TESTED', module: '@jataqi/security', evidence: ['append-only ledger', 'workflow attribution', 'gateway.start posture record + org.data access audit (PR4)'] }),
  cap({ id: 'api', name: 'HTTP API gateway (auth, rate limiting, OpenAPI, TLS, CORS, /v1 versioning)', category: 'foundation', status: 'TESTED', module: '@jataqi/api-gateway', evidence: ['/openapi.json', 'rate limiting', '90+ endpoints', 'native TLS/HTTPS termination + HSTS (PR4)', 'configurable CORS + preflight (PR4)', '/v1 API versioning with backward compatibility (PR4)', 'security headers (nosniff/frame-deny/referrer-policy) (PR4)'] }),
  cap({ id: 'api.tls', name: 'Native HTTPS/TLS termination with secure defaults', category: 'foundation', status: 'TESTED', module: '@jataqi/api-gateway', evidence: ['https.Server with configurable cert/key (inline or file path)', 'minVersion TLSv1.2 default, HSTS over TLS', 'mTLS hooks (requestCert/ca)', '23 gateway-security tests incl. HTTPS + self-signed cert'] }),
  cap({ id: 'api.cors', name: 'Configurable CORS (origins, methods, headers, credentials, preflight)', category: 'foundation', status: 'TESTED', module: '@jataqi/api-gateway', evidence: ['CorsConfig with allow-list origin reflection', 'OPTIONS preflight 204 + access-control-max-age', 'credentials + wildcard incompatibility guard', 'legacy boolean backward-compat'] }),
  cap({ id: 'api.versioning', name: 'API versioning (/v1) with backward compatibility', category: 'foundation', status: 'TESTED', module: '@jataqi/api-gateway', evidence: ['every route reachable at /v1/<path> and legacy /<path>', 'configurable apiVersion segment (disable via false)', 'de-versioned path used for metrics aggregation'] }),
  cap({ id: 'observability', name: 'Observability (metrics, audit, structured logs, RED)', category: 'foundation', status: 'TESTED', module: '@jataqi/metrics', evidence: ['counters/gauges/histograms + Prometheus exposition (text/plain; version=0.0.4)', 'RED metrics: jataqi_requests_total{method,path,status}, jataqi_request_duration_ms histogram, jataqi_requests_in_flight gauge (PR5)', 'fixed text/* content-type serialization so /metrics is valid Prometheus (PR5)', '11 tests'], notes: 'distributed tracing added (PR9): see observability.tracing' }),
  cap({ id: 'observability.tracing', name: 'Distributed tracing (OpenTelemetry-compatible: spans, W3C trace context, OTLP export)', category: 'foundation', status: 'TESTED', module: '@jataqi/tracing', evidence: ['from-scratch OTel-style SDK in pure Node (node:crypto), zero deps', 'spans (attributes/events/status/kind/links) + samplers (always/on/off/ratio/parent-based) + simple & batch processors', 'W3C trace-context propagation: parse/format traceparent+tracestate, extract/inject', 'OTLP/HTTP JSON exporter to a collector (fetch+retry, never throws) + in-memory/console exporters', 'gateway auto-traces each request as a server span and honors incoming traceparent as parent', 'env: OTEL_EXPORTER_OTLP_ENDPOINT / OTEL_SERVICE_NAME / OTEL_TRACES_SAMPLER', 'tests: tracing(25) + gateway-tracing(3)'] }),
  cap({ id: 'communication.providers', name: 'Real email/SMS providers (SendGrid, Twilio, Africa\u2019s Talking)', category: 'foundation', status: 'TESTED', module: '@jataqi/messaging', evidence: ['pure-Node provider clients (fetch) — zero deps', 'SendGrid (email), Twilio (SMS), Africa\u2019s Talking (SMS, KE locale) — each with proper auth + request/response mapping', 'MessagingModule kernel module with getEmailProvider/getSmsProvider', 'env: SENDGRID_API_KEY, TWILIO_ACCOUNT_SID/AUTH_TOKEN/FROM_NUMBER, AFRICAS_TALKING_API_KEY/USERNAME/SENDER_ID', '6 tests: provider API vs mock servers + kernel'] }),
  cap({ id: 'commerce.stripe', name: 'Stripe payment adapter (payment intents, refunds, webhook verification)', category: 'commercial', status: 'TESTED', module: '@jataqi/payments', evidence: ['pure-Node Stripe API client (fetch) — zero deps', 'createPaymentIntent / retrievePaymentIntent / refund with form encoding + metadata flattening', 'webhook signature verification (HMAC-SHA256, constant-time compare, 5-min tolerance)', 'PaymentError with declined flag for card errors', 'env: STRIPE_SECRET_KEY / STRIPE_WEBHOOK_SECRET', '12 tests: API client vs mock server + webhook + kernel module'] }),
  cap({ id: 'realtime', name: 'WebSocket real-time server (RFC 6455, event broadcast, auth)', category: 'foundation', status: 'TESTED', module: '@jataqi/realtime', evidence: ['from-scratch WebSocket (RFC 6455) frame codec + handshake in pure Node — zero deps', 'frame: text/binary/masked/16+64-bit lengths/fragmentation/ping-pong/close', 'RealtimeModule: attach to http.Server, auth-gated upgrade, topic subscription, broadcast', 'gateway auto-attaches on start; auth via session token query param', 'codec(9) + realtime-module(5) tests'] }),
  cap({ id: 'monitoring', name: 'Monitoring stack (Prometheus scrape, alert rules, Grafana dashboard)', category: 'foundation', status: 'TESTED', module: '@jataqi/metrics', evidence: ['Prometheus Operator ServiceMonitor (deploy/monitoring/service-monitor.yaml)', 'alert rules: 5xx error rate, p95 latency, pod-not-ready, readiness failures (prometheus-rules.yaml)', 'Grafana RED dashboard JSON (grafana-dashboard.json)', 'standalone prometheus.yml + datasource provisioning', 'deployment-artifacts validation test (50 checks)'] }),
  cap({ id: 'accreditation', name: 'Legal Operation Mode + accreditation governance (PRX Part L/I/J)', category: 'governance', status: 'TESTED', module: '@jataqi/accreditation', evidence: ['3 operation modes: DEVELOPMENT / PRIVATE_INFRASTRUCTURE / ACCREDITED_PRODUCTION', '15 accreditation domains (registry, registrar, DNS authority, CA root/intermediate/RA, RIR, cloud, VPS, hosting, email, IdP, CDN, marketplace) each with bodies + control frameworks (Part J)', 'Ed25519-signed grants (via @jataqi/provenance crypto) + SHA-256-chained immutable ledger (tamper-evident)', 'gate() enforcement: public-trust capabilities denied without ACTIVE grant + production mode; honest claim verification', 'compliance posture report + bus events', '23 tests'] }),
  cap({ id: 'dns', name: 'Global DNS platform (PRX Part D): authoritative + recursive, DNSSEC, GeoDNS, AXFR, RDAP', category: 'infrastructure', status: 'TESTED', module: '@jataqi/dns', evidence: ['RFC 1035 wire codec in pure Node: header/questions/RRs, name compression (encode+decode pointers), A/AAAA/NS/CNAME/SOA/MX/TXT/SRV/CAA/DNSKEY/DS/RRSIG/NSEC/OPT(EDNS0)', 'AuthoritativeServer: UDP (node:dgram) + TCP (node:net), EDNS0 DO, AXFR zone transfer, analytics', 'RFC 1034 zone semantics: apex SOA/NS, delegation referrals+glue, CNAME chase, wildcard synthesis, NODATA vs NXDOMAIN', 'DNSSEC (RFC 4033/4034/4035): ECDSA P-256 (alg 13) keygen, RRset sign/verify, key tags, DS digest, NSEC denial chain', 'RecursiveResolver: iterative resolution from root, referral following, TTL cache', 'GeoDNS: IPv4/IPv6 CIDR views, round-robin, weighted failover', 'RDAP-style lookup + kernel module + gateway endpoints', '64 tests'] }),
  cap({ id: 'registry', name: 'TLD Registry platform (PRX Part A): domain lifecycle, EPP, RDAP/WHOIS, DNSSEC delegation, data escrow', category: 'infrastructure', status: 'TESTED', module: '@jataqi/registry', evidence: ['Domain lifecycle state machine: ICANN grace periods (ARGP/RGP/pending-delete), renew/restore/softDelete with status prohibitions', 'RFC 5731 domain objects + statuses; DNSSEC DS delegation management', 'EPP (RFC 5730/5731/5734): pure-Node XML codec, 4-byte TCP/TLS framing, login auth, domain check/create/info/renew/delete/update/transfer', 'Transfers (RFC 5731): request/approve/reject, wrong-authInfo rejection, 5-day auto-approve', 'Catalog policy: reserved names, premium pricing, sunrise, trademark claims (TMCH)', 'Data escrow (RFC 8909): signed, point-in-time snapshot deposits + verification', 'RDAP (RFC 7483) output + reporting + sweep + 60 tests'] }),
  cap({ id: 'registrar', name: 'Registrar platform (PRX Part B): search/register/renew/transfer/restore, bulk, portfolio, pricing, billing, KYC, compliance', category: 'infrastructure', status: 'TESTED', module: '@jataqi/registrar', evidence: ['Registrant flows: search, register, renew, transfer, restore; compliance gate before commit', 'Pricing engine: base + premium multiplier + promo codes + multi-year totals', 'Identity/KYC lifecycle (unverified→pending→verified/rejected/suspended)', 'Compliance engine: availability, reserved, trademark claims, KYC, abuse/sanctions screening', 'Bulk registration jobs + portfolio management', 'Billing via @jataqi/commerce (charge + invoice + refund); RegistryConnection abstraction (direct or EPP)', '21 tests'] }),
  cap({ id: 'nova.engine', name: 'NOVA universal game engine — ECS core + deterministic simulation (§3)', category: 'game', status: 'TESTED', module: '@jataqi/game-engine', evidence: ['Entity-Component-System: typed component stores, queries (all/any/none), entity/component events', 'Deterministic fixed-timestep simulation loop with accumulator + spiral-of-death cap', 'Math library: Vec2/3, quaternions (axis-angle, slerp, rotate), Mat4 TRS/multiply', 'Built-in systems: kinematics (linear+angular velocity), lifetime expiry, transform hierarchy', 'World serialize/load (full scene round-trip)', '22 tests'] }),
  cap({ id: 'nova.world', name: 'NOVA procedural world generation — seeded PRNG, noise, biomes, settlements, roads (§5)', category: 'game', status: 'TESTED', module: '@jataqi/game-world', evidence: ['Deterministic seeded PRNG (mulberry32 + FNV hash), Rng helpers (range/int/chance/pick/weighted/fork)', 'Perlin (gradient) + value noise + fractal Brownian motion (fBm)', 'Heightmap elevation/moisture/temperature + Whittaker-style biome classification (12 biomes)', 'Full world gen: regions, named settlements (village/town/city by habitability), MST road network', 'Determinism: identical seed → identical world', '16 tests'] }),
  cap({ id: 'nova.physics', name: 'NOVA physics engine — 3D rigid bodies, collision, impulses, raycasting (§7)', category: 'game', status: 'TESTED', module: '@jataqi/game-physics', evidence: ['Rigid bodies (sphere + AABB colliders), semi-implicit Euler integration, gravity', 'Collision detection + impulse resolution + Baumgarte positional correction + Coulomb friction', 'Distance constraints, ray vs sphere/AABB', 'Deterministic: identical worlds evolve identically', '12 tests'] }),
  cap({ id: 'nova.architect', name: 'NOVA AI game creation — natural-language prompt → design + autonomous build (§2/§19)', category: 'game', status: 'TESTED', module: '@jataqi/game-architect', evidence: ['Prompt parser: NL idea → GameConcept (genre/features/themes/perspective/multiplayer/platforms/art)', 'Design generator: logline, 3-act story, characters, missions, rules, physics profile, economy, UI, sound', '5 AI agents: Director (roadmap/milestones), World Builder (seeded world), Character Designer, Programmer (code modules), Tester (scenarios)', 'Autonomous build pipeline: 8 stages → beta manifest with per-platform targets + deterministic SHA-256 fingerprint', 'Optional LLM refinement hook (deterministic heuristic baseline for offline/test)', '11 tests'] }),
  cap({ id: 'nova.ai', name: 'NOVA NPC intelligence — behavior trees, utility AI, FSM, GOAP, personality/emotion/dialogue (§6)', category: 'game', status: 'TESTED', module: '@jataqi/game-ai', evidence: ['Behavior trees: Sequence/Selector/Parallel + Inverter/Repeater/UntilFail/Succeeder decorators, fluent builder, memory via blackboard', 'Utility AI: weighted considerations + response curves + bias; Finite State Machine with guarded transitions', 'GOAP-lite planner: least-cost action sequence over world state (autonomous agents)', 'Personality (Big-Five) + PAD emotion model + directed relationship graph', 'Branching dialogue with guards/effects + transcript', 'NpcAgent (pluggable driver) + NpcSystem over the ECS', '25 tests'] }),
  cap({ id: 'nova.net', name: 'NOVA multiplayer netcode — authoritative rooms, snapshot/delta sync, prediction, matchmaking, anti-cheat (§9)', category: 'game', status: 'TESTED', module: '@jataqi/game-net', evidence: ['Authoritative Room over a game-engine ECS World: join/leave, input queue, fixed-step tick, anti-cheat gating', 'Replication: full snapshots + compressed deltas (snapshot differencing); configurable snapshot rate + history', 'NetClient: client-side prediction + server reconciliation (replays pending inputs on own entity)', 'Matchmaker: skill-proximity + region grouping, party support', 'Anti-cheat validators: rate-limit, magnitude (speed-hack), shape; composable chain', 'Loopback transport (lossless ordered) for deterministic offline testing; WebSocket/UDP pluggable', '9 tests incl. full Room↔NetClient convergence loop'] }),
  cap({ id: 'nova.economy', name: 'NOVA game economy + marketplace — currencies, wallets, immutable ledger, royalties (§10/§11)', category: 'game', status: 'TESTED', module: '@jataqi/game-economy', evidence: ['Virtual currencies (soft/premium/hard) + the four wallet kinds: player / creator / developer / marketplace', 'Exact bigint minor-unit balances (no float drift); credit/debit/transfer/mint/burn', 'Tamper-evident SHA-256-chained transaction ledger (self-verifying)', 'Royalty-paying asset marketplace: fee + per-share creator royalties + seller net split, atomic purchase, licensing', 'GameEconomyModule kernel integration + economy events', '13 tests'] }),
  cap({ id: 'nova.audio', name: 'NOVA sound & music AI — procedural synthesis, generative music, SFX, spatial, adaptive layers (§12)', category: 'game', status: 'TESTED', module: '@jataqi/game-audio', evidence: ['Real procedural synthesis: oscillators (sine/square/saw/triangle/noise) + ADSR envelopes + pitch/note helpers', 'Generative music: deterministic seeded composer (bass + arpeggio + melody over a scale + chord progression)', 'Procedural SFX (explosion/laser/coin/footstep/impact/blip)', '3D spatial mixing (distance attenuation + constant-power pan) and adaptive intensity crossfade layers', 'Real WAV encoding (PCM16 RIFF/WAVE) — verified valid headers; identical seed → identical audio', '14 tests; produces a playable ~1.6MB stereo theme.wav'] }),
  cap({ id: 'nova.esports', name: 'NOVA esports & competition — ratings, leaderboards, tournaments, replays, spectator (§13)', category: 'game', status: 'TESTED', module: '@jataqi/game-esports', evidence: ['Elo ratings (expected score + update) + 7 rank tiers (Bronze→Grandmaster)', 'Leaderboard: ranked ladder, W/L/D records, seasons, tier distribution', 'Tournaments: single-elimination (seeds + byes) and Swiss (no-rematch pairing + Buchholz tiebreak)', 'Replay recording/playback with tamper-evident SHA-256 fingerprinting', 'Live spectator match bus + EsportsModule kernel integration', '14 tests'] }),
  cap({ id: 'nova.publish', name: 'NOVA publishing — deterministic signed build pipeline + store submission lifecycle (§14)', category: 'game', status: 'TESTED', module: '@jataqi/game-publish', evidence: ['11 build targets (android/ios/windows/mac/linux/playstation/xbox/nintendo/web/cloud/vr) → store mapping', 'Deterministic SHA-256 artifact checksums (same spec → same artifact) + Ed25519 signing + verification', 'Build stage log + aggregated build fingerprint; semver parse/bump/compare', 'Store submission lifecycle (draft→submitted→in-review→approved/rejected→published) with enforced transitions', 'One-click build+submit; PublishModule kernel integration + events', '11 tests'] }),
  cap({ id: 'nova.liveops', name: 'NOVA live game operations — analytics, A/B experiments, flags, events, offers, config (§15)', category: 'game', status: 'TESTED', module: '@jataqi/game-liveops', evidence: ['Analytics: telemetry ingestion, sessions, DAU/WAU/MAU, new vs returning, cohorts + D1/D7/D30 retention, funnels, economy, match stats, revenue (ARPDAU/ARPPU/LTV), query + aggregate', 'A/B/n + multivariate experiments: stable hash assignment, traffic allocation, conversion + z-test significance, lifecycle (draft/running/paused/completed)', 'Feature flags + canary rollouts + segment targeting', 'Live events (active windows + daily/weekly recurrence), targeted offers (show/purchase + conversion), remote config + experiment overrides + hot-reload, season management', '8 live-ops bus events; LiveOpsModule kernel integration', '29 tests'] }),
  cap({ id: 'design-system', name: 'JATA Qi universal design language — tokens, light/dark themes, WCAG AA color science, CSS generation', category: 'ui', status: 'TESTED', module: '@jataqi/design-system', evidence: ['Canonical tokens: semantic color (light+dark), typography scale, 8px spacing grid, radius (16–24px premium), elevation (z0–z5 + glass), motion, breakpoints, z-index', 'WCAG AA color science: hex<->rgb, relative luminance, contrast ratio, passesAA/AAA, legible-foreground picker, mix/darken/lighten', 'Theme resolution: light/dark bundles + per-product BrandOverride (derives primary-dim + legible text) + time-of-day adaptive mode', 'CSS generation: deterministic --jq-* custom properties for both themes + base reset (focus-visible/a11y) + component primitives (buttons/cards/tables/forms/nav/sidebar/badges/dialog/toast/loading) + glass/elevation utilities', 'DesignSystemModule kernel integration + theme/brand events', '21 tests'] }),
  cap({ id: 'universal-wallet', name: 'JATA Qi Universal Wallet — consolidated double-entry multi-currency wallet (Phase 2)', category: 'foundation', status: 'TESTED', module: '@jataqi/universal-wallet', evidence: ['Consolidates 3 legacy systems (finance.Wallet, commerce.credits, game-economy.WalletStore) behind one unified engine with backward-compat adapters', 'Double-entry SHA-256-chained ledger (immutable, tamper-evident, self-verifying)', '11 default currencies: fiat (KES/USD/EUR/GBP), crypto (KRT/USDT/USDC), virtual (POINTS/CREDIT/GEMS/COINS); custom currency registration', 'Operations: deposit, withdraw, transfer (atomic), grant, consume, escrow (hold/release/refund), freeze/close', 'Wallet roles: player, creator, developer, marketplace, treasury, escrow, system', 'Multi-currency balances per wallet, transaction history, system summary', 'UniversalWalletModule kernel integration + wallet/transfer/escrow bus events', '21 tests'] }),
  cap({ id: 'link-intelligence', name: 'JATA Qi Universal Link Intelligence — classify, extract, gap-analyze, propose, validate, evolve (all 10 phases)', category: 'intelligence', status: 'TESTED', module: '@jataqi/link-intelligence', evidence: ['Phase 1 Classifier: detects source type (github/gitlab/npm/pypi/openapi/graphql/youtube/pdf/markdown/html/json/xml/rss/paper/rfc/docs), language (20+), framework, domain, version, license, title, dependencies, confidence — from URL + content patterns', 'Phase 2 Extractor: 19 structured intelligence dimensions (architectures, design patterns, algorithms, data models, APIs, services, security models, auth mechanisms, AI workflows, UI systems, deployment models, DevOps practices, performance optimizations, testing methodologies, domain concepts, business capabilities, infrastructure patterns, code snippets)', 'Phase 4 Gap Analyzer: 10 gap indicators (SSO/OIDC/SAML, ABAC/ReBAC, GraphQL, webhooks, African payments, blockchain, data lake, chaos engineering, LSP, service mesh) compared against the platform capability set; severity + value scoring', 'Phase 3+9: stores intelligence in knowledge-service + memory engine (graceful degradation)', 'Phase 5: generates governed proposals from gaps (business/technical value, complexity, risk, effort, test/rollback strategy)', 'Phase 6: validates proposals (static analysis, license compliance, architecture validation, security scan, governance gate)', 'Phase 7: submits approved proposals to self-evolution framework for governed implementation', 'LinkIntelligenceModule: kernel integration + classified/extracted/gaps/proposal/validated/knowledge bus events', '19 tests'] }),
  cap({ id: 'multimodal-intelligence', name: 'JATA Qi Universal Multimodal Intelligence — acquisition, normalization, gap detection, self-evolution (all modalities)', category: 'intelligence', status: 'TESTED', module: '@jataqi/multimodal-intelligence', evidence: ['11 modality pipelines: text, document, image, audio, video, code, web, device, enterprise, API, link — each with specialized extraction', 'SemanticKnowledge: concepts, relationships, facts, procedures, data models, APIs, security patterns, optimizations, workflows, code snippets, confidence scoring', 'Authorization gates: secure-by-default; sources requiring auth are blocked until explicitly authorized; expiry checking; legal basis tracking', 'Privacy classification: restricted (passwords/credit cards/PII), confidential (personal data), internal, public — from content scanning', 'Capability gap detection: 10 gap indicators (SSO, ABAC/ReBAC, GraphQL, African payments, blockchain, data lake, chaos eng, service mesh, LSP, zero trust)', 'Knowledge storage: delegates to knowledge-service + memory engine (graceful degradation)', 'Source management: register/authorize/revoke sources; batch acquisition; direct acquisition without pre-registration', 'MultimodalIntelligenceModule: kernel integration + acquired/stored/gaps/unauthorized bus events + summary metrics', '22 tests'] }),
  cap({ id: 'memory', name: 'JATA Qi Digital Memory Engine — unified governed platform-event memory (CLP Phase 1)', category: 'intelligence', status: 'TESTED', module: '@jataqi/memory', evidence: ['26 normalized memory categories (commands, prompts, AI responses, workflows, API traffic, navigation, search, dashboard, auth, billing, security, errors, incidents, …)', 'Tenant isolation (org-scoped queries), correlation IDs, session tracking, metadata extraction, timestamping', 'Governance: per-org policy (allow/block lists, disable), consent gating, retention TTLs + sweep', 'Content-hash dedup with revision versioning (includes userId to prevent cross-user collisions); inverted token index + keyword-ranked search', 'Privacy: export (SAR) + right-to-delete; stats by category/org; cross-org queryAll for internal platform services', 'DigitalMemoryModule: storage persistence + memory.recorded/expired/purged bus events + opt-in platform-bus collection', 'Reuses core-kernel + storage; composes (not duplicates) self-evolution/privacy/knowledge/analytics', '18 tests'] }),
  cap({ id: 'learning', name: 'JATA Qi Continuous Learning + Personalization — insights, recommendations, behavior adaptation (CLP Phase 2/6)', category: 'intelligence', status: 'TESTED', module: '@jataqi/learning', evidence: ['LearningEngine: 7 analysis dimensions (feature adoption/decline, user journeys, workflow completion/abandonment, error frequency, search failures, UI friction, automation opportunities) over the memory stream', 'Governed recommendations: maps insights to actionable recommendations with category/impact/priority + review lifecycle (proposed→accepted/rejected→deployed)', 'PersonalizationEngine: per-user preference profiles (explicit > derived > default) + behavior-derived adaptation (nav order, search boost, shortcut/widget suggestions, preferred AI model)', 'ContinuousLearningModule: kernel integration with @jataqi/memory (pulls governed events), emits learning.insights.generated/recommendation.proposed/reviewed/personalization.user.adapted', '12 tests; composes memory (not duplicate analytics)'] }),
  cap({ id: 'ai-learning', name: 'JATA Qi AI Learning — prompt registry, quality tracking, drift detection, model benchmarking (CLP Phase 3)', category: 'intelligence', status: 'TESTED', module: '@jataqi/ai-learning', evidence: ['PromptRegistry: versioned templates with {{variable}} extraction + lifecycle (draft→reviewed→active→deprecated) + variable rendering', 'QualityTracker: per-response outcomes (accepted/edited/rejected, rating 1-5, latency, cost, confidence, tokens) → aggregated metrics (acceptance rate, avg rating/latency/cost, p50/p95 percentiles)', 'DriftDetector: sliding-window quality comparison (acceptance rate drop, rating degradation, latency spike) with warning/critical severity alerts', 'Model benchmarking: ranks models/providers by acceptance rate + cost-per-accept + latency percentiles; best-model recommendation', 'AiLearningModule: kernel integration with @jataqi/memory (feeds AI events to DME) + bus events (prompt.created/activated, quality.recorded, drift.detected)', '15 tests; composes memory (not duplicate evals/llm-gateway)'] }),
  cap({ id: 'mfa-sso', name: 'MFA (TOTP RFC 6238) + session elevation', category: 'foundation', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/mfa', evidence: ['TOTP enrollment + verification (RFC 6238), backup codes, trusted devices, brute-force lockout, session elevation, 16 tests'], notes: 'no SSO/OAuth/OIDC integration yet; no SAML; no WebAuthn' }),
  cap({ id: 'multi-tenancy', name: 'Multi-tenancy & organizations (tenant isolation)', category: 'foundation', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/organizations', evidence: ['organizations, memberships, roles, invitations, role gating — 8 tests', 'platform-wide TenantScope isolation primitive (PR4) — tenant:<id>: partitioning across all drivers', 'enforced org-scoped /org/data endpoints with membership checks + 403 on cross-tenant access (PR4)'], notes: 'org model + storage isolation primitive + gateway enforcement are real & tested; not every domain-module store has been migrated to the TenantScope yet' }),
  cap({ id: 'security.tenant-isolation', name: 'Multi-tenant storage isolation enforcement', category: 'foundation', status: 'TESTED', module: '@jataqi/storage', evidence: ['TenantScope (collection/namespace/blobStore) partitioned by tenant id', 'tenantPartitionName validation rejects path-separator/invalid ids', '8 tests: cross-tenant invisibility on memory + filesystem drivers, isolation across simulated restart', 'gateway enforces membership before exposing tenant scope (403 for non-members)'] }),
  cap({ id: 'module-registry', name: 'Universal module registry', category: 'foundation', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/plugins', notes: 'plugin registry exists; formal module manifest registry PLANNED' }),
  cap({ id: 'infrastructure.terraform', name: 'Terraform IaC (EKS, RDS PostgreSQL, S3 backups, Secrets Manager)', category: 'foundation', status: 'TESTED', module: '-', evidence: ['deploy/terraform/: VPC + EKS cluster + RDS PostgreSQL (multi-writer, encrypted) + S3 backup bucket + Secrets Manager', 'variables.tf with production defaults; outputs.tf exposes cluster + DB endpoints', 'terraform.tfvars.example for production (Multi-AZ DB, 30-day retention)', '4 structural validation tests'] }),
  cap({ id: 'kubernetes', name: 'Kubernetes deployment (manifests, Helm, probes, HPA, PDB, NetworkPolicy)', category: 'foundation', status: 'TESTED', module: '-', evidence: ['deploy/k8s: namespace/configmap/secret/SA+RBAC/StatefulSet/service/ingress/HPA/PDB/NetworkPolicy + Kustomize base', 'deploy/helm/jataqi: parameterized chart (values, helpers, 8 templates, NOTES)', 'liveness /livez + readiness /readyz + startup probes; non-root, dropped ALL caps, readOnlyRootFilesystem, resource limits, PVC', '50-check deployment-artifacts validation test'] }),
  cap({ id: 'horizontal-scaling', name: 'Horizontal scaling (stateless gateway + shared store)', category: 'foundation', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/api-gateway', evidence: ['gateway is stateless: sessions/users/apikeys/org-data in shared store; any replica authenticates any request', '7-test suite: token issued on A valid on B, API key cross-instance, org tenant data shared, revocation propagates immediately, both ready', 'SQLite WAL = concurrent shared reads + single writer'], notes: 'multi-writer scale-out now supported via the PostgreSQL driver (PR8); SQLite remains single-writer / vertically scalable' }),

  // --- Intelligence (P1) ---
  cap({ id: 'qil', name: 'QiL orchestration language (lexer/parser/compiler)', category: 'intelligence', status: 'TESTED', module: '@jataqi/qil', evidence: ['19 tests', 'execution-plan DAG'] }),
  cap({ id: 'memory', name: 'Agent & session memory', category: 'intelligence', status: 'TESTED', module: '@jataqi/agent-runtime', evidence: ['ConversationManager', 'session memory'] }),
  cap({ id: 'knowledge', name: 'Knowledge fabric (ingest/chunk/retrieve/graph)', category: 'intelligence', status: 'TESTED', module: '@jataqi/knowledge-service', evidence: ['33 tests across knowledge + graph'] }),
  cap({ id: 'agents', name: 'Agent runtime (ReAct loop, tools, LLMs)', category: 'intelligence', status: 'TESTED', module: '@jataqi/agent-runtime', evidence: ['10 tests', 'Echo/Scripted/OpenAI LLMs'] }),
  cap({ id: 'workflows', name: 'Workflow engine (QiL plan execution, durable history)', category: 'intelligence', status: 'TESTED', module: '@jataqi/orchestrator', evidence: ['8 tests', 'durable run store'] }),
  cap({ id: 'model-abstraction', name: 'Model abstraction & routing (auto-wired via ModelRouter + SovereignRouter)', category: 'intelligence', status: 'TESTED', module: '@jataqi/model-registry', evidence: ['catalog + selector + ModelRouter (circuit breaker, health, fallback, policy enforcement)', 'SovereignRouter: privacy-aware routing, local/remote, EchoLLM fallback', 'auto-wired into agent runtime via model-runtime module'] }),
  cap({ id: 'teams', name: 'Multi-agent orchestration (parallel/sequential/consensus)', category: 'intelligence', status: 'TESTED', module: '@jataqi/teams', evidence: ['5 tests'] }),
  cap({ id: 'tool-intelligence', name: 'Universal AI Tool Intelligence Layer', category: 'intelligence', status: 'TESTED', module: '@jataqi/tool-intelligence', evidence: ['registry, adapters, risk gating, fallback, approvals — 8 tests'] }),
  cap({ id: 'compute', name: 'Scientific/math compute (stats, regression, optimization)', category: 'intelligence', status: 'TESTED', module: '@jataqi/compute', evidence: ['11 tests', 'agent tools'] }),
  cap({ id: 'simulation', name: 'Simulation engine (Monte-Carlo)', category: 'intelligence', status: 'TESTED', module: '@jataqi/simulation', evidence: ['7 tests', 'probabilistic outputs'] }),
  cap({ id: 'scheduler', name: 'Compute scheduler + adaptive router', category: 'intelligence', status: 'TESTED', module: '@jataqi/scheduler', evidence: ['priority queue, targets, profile router'] }),

  // --- Developer (P2) ---
  cap({ id: 'cli', name: 'Developer CLI', category: 'developer', status: 'TESTED', module: '@jataqi/cli', evidence: ['serve, ask, models, simulate, plugins'] }),
  cap({ id: 'sdk', name: 'TypeScript SDK (typed HTTP client)', category: 'developer', status: 'TESTED', module: '@jataqi/sdk', evidence: ['typed JataQiClient with 22 namespace clients covering all gateway endpoints', 'auth, health, identity, readiness, knowledge, agent, qil, workflow, tools, devices, twins, models, simulate, team, commerce, org, notifications, flags, gov, media, mfa', '22 integration tests against real server', 'examples/basic-usage.mjs'], notes: 'no Python SDK yet; no WebSocket client; local/embedded mode requires importing @jataqi/cli directly' }),
  cap({ id: 'evals', name: 'AI evaluation platform (suites, metrics, regression)', category: 'developer', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/evals', evidence: ['eval suites, built-in metrics (exact/contains/token-overlap/regex), run scoring, regression comparison — 7 tests'], notes: 'no bias/safety/hallucination-specific evaluators yet; no scheduled evals; no dashboard' }),
  cap({ id: 'web-ui', name: 'Web admin console (responsive SPA, 16 dashboard views)', category: 'developer', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/web-ui', evidence: ['responsive SPA with auth, dashboard, health, identity, readiness, agents, workflows, tools, models, knowledge, commerce, organizations, notifications, governance, devices, twins, flags — 8 tests incl. gateway-served static files'], notes: 'vanilla JS (no React); no mobile native; no real-time WebSocket; served by API gateway at /ui' }),
  cap({ id: 'quality.e2e', name: 'End-to-end vertical-slice test suite', category: 'developer', status: 'TESTED', module: '@jataqi/cli', evidence: ['e2e-vertical-slice.test.ts boots the full 56-module stack via createJataQi and drives the complete journey over real HTTP', '15 tests: probes, auth, identity, org/tenant data, objective→workflow→audit, QiL+agent, tools, commerce, governance, notifications, backup, metrics, session mgmt, /v1 versioning'] }),
  cap({ id: 'quality.performance', name: 'Performance benchmarks (latency p50/p95/p99, throughput, memory)', category: 'developer', status: 'TESTED', module: '@jataqi/cli', evidence: ['performance.test.ts: serial + concurrent latency percentiles, throughput (req/s), memory-growth leak check over 2000 requests', '4 tests with bounded thresholds (JATAQI_SKIP_PERF opt-out)'] }),
  cap({ id: 'quality.security-testing', name: 'Security penetration tests (auth, RBAC, tenant, input, CORS, rate-limit)', category: 'governance', status: 'TESTED', module: '@jataqi/api-gateway', evidence: ['security.test.ts: auth bypass, forged tokens, RBAC escalation, tenant-isolation bypass attempts, revoked-token reuse, oversized/malformed bodies, CORS spoofing, SQL/metachar injection, rate limiting, security headers — 16 tests'] }),
  cap({ id: 'quality.chaos', name: 'Chaos / resilience engineering (degradation, sanitized errors, concurrency, restart)', category: 'governance', status: 'TESTED', module: '@jataqi/api-gateway', evidence: ['chaos.test.ts: absent-module graceful 501, missing-dependency reporting, sanitized 500 (no stack leak), concurrent mutation integrity, restart resilience — 7 tests', 'robustness fix: gateway drains oversized request bodies so rejected requests do not corrupt keep-alive connections'] }),

  // --- Commercial (P3) ---
  cap({ id: 'commerce', name: 'Commercial & product packaging engine (plans, subscriptions, entitlements, Stripe payments, credits, marketplace)', category: 'commercial', status: 'TESTED', module: '@jataqi/commerce', evidence: ['configurable catalogue/plans/editions', 'subscription + trial lifecycle', 'quota enforcement', 'credits', 'invoices/tax/discount', 'marketplace commission split', 'analytics — 12 tests', 'Stripe payment provider bridge wired (PR3): charge via PaymentIntent, refund, setPaymentProvider()'] }),
  cap({ id: 'marketplace', name: 'Marketplace storefront & seller economy', category: 'commercial', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/commerce', notes: 'purchase + commission + payout ledger implemented; no storefront UI, discovery, ratings, or real payouts' }),
  cap({ id: 'organizations', name: 'Organizations & teams', category: 'commercial', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/organizations', evidence: ['organizations, memberships, hierarchical roles, invitations, tenant scoping — 8 tests'], notes: 'model + API real; full platform-wide tenant isolation enforcement not yet applied to every module store' }),

  // --- Enterprise (P4) ---
  cap({ id: 'enterprise', name: 'Enterprise OS (CRM/ERP/HR/Finance/Procurement)', category: 'enterprise', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/enterprise', evidence: ['org units, records with typed data, workflows — 4 tests'], notes: 'no real CRM/ERP integrations; no multi-tenant data isolation enforcement' }),
  cap({ id: 'finance', name: 'Financial intelligence (wallets, ledgers, transactions, reconciliation)', category: 'enterprise', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/finance', evidence: ['immutable append-only ledger, wallets, credit/debit/transfer/reverse, reconciliation, governance-gated — 12 tests'], notes: 'real ledger engine; no real payment provider integration; no FX/multi-currency conversion; no regulated financial services' }),
  cap({ id: 'supply-chain', name: 'Supply chain intelligence (suppliers, inventory, POs, deliveries)', category: 'enterprise', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/supply-chain', evidence: ['suppliers+ratings, inventory with low-stock alerts, purchase orders with approval, deliveries with auto-stock-in — 3 tests'], notes: 'no demand forecasting, no logistics optimization, no multi-warehouse' }),

  // --- Domain intelligence (P5) ---
  cap({ id: 'education', name: 'Education intelligence (courses, lessons, enrollments, progress, student privacy)', category: 'domain', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/education', evidence: ['courses with levels, lessons, enrollments, progress tracking with completion, auto-complete at 100% — 7 tests'], notes: 'no AI tutors, no assessment grading, no institutional dashboards' }),
  cap({ id: 'health', name: 'Health intelligence (records, vitals, education — NOT a diagnostic tool)', category: 'domain', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/health', evidence: ['health records (restricted sensitivity), vital signs tracking, educational content with disclaimer, consent gate — 6 tests'], notes: 'information management ONLY; explicitly does NOT diagnose or prescribe; no clinical validation; consent enforced via privacy module when present' }),
  cap({ id: 'research', name: 'Research & scientific discovery (workspaces, experiments, literature, hypotheses)', category: 'domain', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/research', evidence: ['projects, experiments with status/results, literature refs with tags, hypothesis tracking (AI-flagged) — 7 tests'], notes: 'no literature search/PDF parsing; no reproducibility tracking automation; no collaboration features' }),
  cap({ id: 'communication', name: 'Communication intelligence (email/SMS/messaging adapters, templates)', category: 'domain', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/communication', evidence: ['adapter-based channels (email/sms/push/whatsapp/inapp), template interpolation, message log — 8 tests'], notes: 'no real email/SMS providers wired (adapter abstraction); no consent/anti-spam enforcement' }),
  cap({ id: 'multimedia', name: 'Multimedia Intelligence Suite (music, story, image, video, film)', category: 'domain', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/multimedia', evidence: ['projects, creative jobs, async rendering queue, versioned assets, licensing/watermark/provenance, voice-clone consent, governance gate, marketplace publish — 13 tests'], notes: 'text-based creative output (lyrics/story/screenplay) works end-to-end; audio/video/image synthesis requires external Renderer adapters (none wired by default — abstraction only)' }),
  cap({ id: 'creative', name: 'Creative intelligence (image/video/audio gen)', category: 'domain', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/multimedia', notes: 'rendering pipeline + asset model implemented; no live generative model providers connected' }),
  cap({ id: 'multimodal', name: 'Multimodal (vision/audio/video) model adapter platform', category: 'domain', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/multimodal', evidence: ['adapter-based provider routing for 17 task types (caption, classify, OCR, STT, TTS, embed, generate, reason, etc.)', 'built-in deterministic text provider + mock image-gen/audio providers', 'caching by input hash, result storage — 18 tests'], notes: 'no real vision/audio/video model providers wired (adapter abstraction only); no streaming; no real-time inference' }),

  // --- Physical / infrastructure (P6) ---
  cap({ id: 'robotics', name: 'Robotics & device registry', category: 'physical', status: 'TESTED', module: '@jataqi/robotics', notes: 'device/mission/telemetry abstraction; no real hardware connected' }),
  cap({ id: 'digital-twin', name: 'Digital twin framework', category: 'physical', status: 'TESTED', module: '@jataqi/digital-twin', evidence: ['7 tests', 'step/project'] }),
  cap({ id: 'iot', name: 'IoT (device registry, telemetry, commands)', category: 'physical', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/iot', evidence: ['devices, telemetry, commands with ack, offline detection — 5 tests'], notes: 'no real sensor/actuator hardware; abstract device protocol' }),
  cap({ id: 'cloud-devops', name: 'Cloud & DevOps (deployments, resources, logs, rollback)', category: 'physical', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/cloud-devops', evidence: ['deployment lifecycle (plan→deploy→rollback), infra resources, deployment logs — 5 tests'], notes: 'no real K8s/Docker integration; simulated deployment completion' }),
  cap({ id: 'smart-cities', name: 'Smart cities (services, metrics, threshold alerts)', category: 'physical', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/smart-cities', evidence: ['city services, metrics with threshold alerts, sustainability tracking — 3 tests'], notes: 'no real city infrastructure integration' }),
  cap({ id: 'environment', name: 'Environmental intelligence (monitoring, alerts, sustainability)', category: 'physical', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/environment', evidence: ['monitoring stations, readings with threshold alerts (severity-scaled), sustainability metrics — 4 tests'], notes: 'no real sensor integration, no satellite data, no climate modeling' }),

  // --- Governance & safety ---
  cap({ id: 'notifications', name: 'Notification engine (in-app + real email/SMS via SendGrid/Twilio/Africa\u2019s Talking, preferences, rate limits)', category: 'foundation', status: 'TESTED', module: '@jataqi/notifications', evidence: ['multi-channel delivery, inbox, preferences, rate limits, event-driven — 6 tests', 'real provider bridges wired: SendGrid email channel + Twilio/Africa\u2019s Talking SMS channel (PR3)', 'provider bridge tests: email(3) + SMS(2) + Stripe payment(3)'] }),
  cap({ id: 'governance', name: 'Policy & compliance registry', category: 'governance', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/policies', evidence: ['declarative policy engine (allow/deny/require_approval)', 'compliance control registry + framework summary', '8 tests'], notes: 'engine + controls real; not yet wired as a mandatory gate on every action across all modules' }),
  cap({ id: 'policy-governance', name: 'Policy & governance control plane (versioned, tenant-aware, precedence, agent/tool governance)', category: 'governance', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/policy-governance', evidence: ['rich versioned policy model + multi-effect engine', 'precedence (deny>safety>legal>org>role>entitlement; sensitive default-deny)', 'MANDATORY pre-execution gate wired into orchestrator (every step) + tool-intelligence (every invoke)', 'org/role/entitlement integration, simulation, overrides, autonomy levels, agent governance', 'observability: per-decision metrics counter + durationMs + evaluation history trace', 'integration tests prove deny/require-approval block runtime actions'], notes: 'engine + registry + mandatory enforcement real & tested; no admin UI; conditions DSL intentionally small' }),
  cap({ id: 'feature-flags', name: 'Feature flags (deployment rollout, separate from entitlements)', category: 'foundation', status: 'TESTED', module: '@jataqi/feature-flags', evidence: ['deterministic % rollout, set/check — 4 tests'] }),
  cap({ id: 'data-privacy', name: 'Data privacy (classification, retention, consent, SARs)', category: 'governance', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/privacy', evidence: ['classification + AI-restriction check, retention, consent, subject-access requests — 4 tests'], notes: 'primitives real; not yet enforced platform-wide on every store or AI context path' }),
  cap({ id: 'human-oversight', name: 'Human approval engine (high-risk actions)', category: 'governance', status: 'TESTED', module: '@jataqi/tool-intelligence', evidence: ['approval gating for R4/R5 tools'] }),
  cap({ id: 'provenance', name: 'Creator identity & cryptographic provenance (JQ-CIP)', category: 'governance', status: 'TESTED', module: '@jataqi/provenance', evidence: ['Ed25519 signed root manifest', 'append-only hash-chained ledger', 'tamper detection', 'key rotation/revocation'], notes: 'creator = GITANYA K; private signing key kept out of the repo' }),
  cap({ id: 'conversations', name: 'Conversation management (persistent history, folders, pins, search, sharing, export, editing, regeneration)', category: 'foundation', status: 'TESTED', module: '@jataqi/conversations', evidence: ['ConversationsModule: create/get/list/delete with folder organization, pinned sorting, archive', 'messages: add/edit/delete-after (regeneration), auto-title, tool calls, usage tracking, edit timestamps', 'folders: create/list/delete with conversation reassignment', 'search: full-text across titles + messages + tags', 'sharing: share/unshare with public share ID retrieval', 'export: JSON/Markdown/text formats', 'stats: per-user conversation/message/pin counts', '13 tests covering all operations + event emission'] }),
  cap({ id: 'model-runtime', name: 'Sovereign model runtime (local/remote lifecycle, GPU detection, circuit breaker, privacy routing)', category: 'foundation', status: 'TESTED', module: '@jataqi/model-runtime', evidence: ['SovereignRouter: local (Ollama/vLLM) + remote (OpenAI/Anthropic/Google/xAI/DeepSeek/Mistral) with automatic fallback to EchoLLM', 'Privacy engine: sensitive data forced to local models', 'GPU detection via nvidia-smi; CPU fallback automatic', 'Circuit breaker: health tracking, EWMA latency, error state after sustained failures', 'Universal provider adapters (7 remote + 2 local) — zero external deps (fetch)', 'completeRouted() returns routing decision + response for audit', 'Always sovereign: operates with zero external providers', '13 tests: routing(7), fallback(2), health(2), sovereign operation(2)'] }),
  cap({ id: 'ai-safety', name: 'AI safety framework (prompt injection guard, PII detection, toxicity screening, agent loop limits)', category: 'governance', status: 'TESTED', module: '@jataqi/ai-safety', evidence: ['PromptGuard: heuristic detection of injection overrides, system prompt extraction, jailbreak (DAN), code exec, data exfiltration', 'PII detection (credit card, SSN, email, phone) with redaction/sanitization', 'Toxicity screening (threats, self-harm, hate speech, profanity)', 'AiSafetyModule kernel module with event emission on violations', 'configurable blockAt threshold, maxInputLength, detectPII/detectToxicity toggles', '24 tests: injection(9) + PII(6) + toxicity(3) + config/edge(6)'] }),
  cap({ id: 'cyberdefense', name: 'Cybersecurity & threat defense (indicators, vulnerabilities, incidents)', category: 'governance', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/cyberdefense', evidence: ['threat indicators with value-checking, vulnerability lifecycle (open→remediated), incident management (open→resolved), security event log — 4 tests'], notes: 'no real SIEM integration, no automated remediation, no SOC dashboard' }),

  // --- Global / sovereign (P7) ---
  cap({ id: 'sovereign', name: 'Sovereign deployment (jurisdiction profiles, data residency, compliance, failover)', category: 'global', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/sovereign', evidence: ['9 built-in jurisdiction profiles (KE/EU/US/CN/IN/NG/ZA/SA/GOV), custom profiles, multi-region with failover, compliance checks (residency/cross-border/classification), sovereign policies — 20 tests'], notes: 'profiles are configurable engineering templates, not legal advice; no real multi-region infrastructure; no real KMS integration' }),
  cap({ id: 'localization', name: 'Localization (locales, currencies, translations)', category: 'global', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/localization', evidence: ['locales, currencies, translation CRUD with variable interpolation, money formatting — 5 tests'], notes: 'no ICU/CLDR integration; no RTL rendering' }),
  cap({ id: 'disaster-recovery', name: 'Disaster recovery (snapshots, restore, verification)', category: 'global', status: 'PARTIALLY_IMPLEMENTED', module: '@jataqi/disaster-recovery', evidence: ['point-in-time snapshots of storage namespaces, restore with hash verification, retention — 4 tests', 'scheduled backup automation (PR4): interval scheduler + retention pruning + on-demand runNow'], notes: 'automated scheduling, restore verification & retention now implemented (PR4); no cross-region replication, no streaming backup' }),
  cap({ id: 'disaster-recovery.scheduler', name: 'Scheduled backup automation (interval + retention + notifications)', category: 'global', status: 'TESTED', module: '@jataqi/disaster-recovery', evidence: ['BackupScheduleConfig: namespaces/intervalMs/retention/notify', 'runBackupCycle + startScheduler + runNow', 'audit record + notifications-module notice per run', '7 tests incl. retention pruning, event emission, shutdown cleanup', 'env-driven via BACKUP_NAMESPACES/BACKUP_INTERVAL_MS; gateway /backup + /backup/schedule endpoints'] }),

  // --- Frontier (P8) — research/simulation only ---
  cap({ id: 'quantum', name: 'Quantum computing integration', category: 'frontier', status: 'RESEARCH_ONLY', notes: 'scheduler models a quantum target tag; no real quantum hardware' }),
  cap({ id: 'space', name: 'Space / interplanetary intelligence', category: 'frontier', status: 'RESEARCH_ONLY' }),
  cap({ id: 'self-evolution', name: 'Self-evolution engine (observation, analysis, proposals, experiments, governed autonomous optimization + intelligence integration)', category: 'frontier', status: 'TESTED', module: '@jataqi/self-evolution', evidence: ['Full lifecycle: observe → analyze → propose → governance approval → experiment (AB/canary/shadow/sim) → deploy → rollback + lessons learned + explainability + cycle-cap safety — 16 existing tests', 'CLP Phase 7 enhancement: observeFromMemory (ingests DME events as observations), generateFromInsights (creates proposals from @jataqi/learning insights), generateFromDrift (creates proposals from @jataqi/ai-learning drift alerts), runEvolutionCycle (full pipeline: memory → analyze → proposals from analysis + insights + drift)', 'Graceful degradation: all new methods no-op when intelligence modules are not registered; backward-compatible with all existing APIs', '23 tests (16 original + 7 intelligence integration)'] }),
];
