import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { createJataQi } from '../src/bootstrap.js';
import { AgentRuntimeModule } from '@jataqi/agent-runtime';
import { KnowledgeService } from '@jataqi/knowledge-service';
import { KnowledgeGraphModule } from '@jataqi/knowledge-graph';
import { CommercialControlPlaneModule } from '@jataqi/commercial-control-plane';
import { AutonomousActionRuntimeModule } from '@jataqi/autonomous-action-runtime';
import { ExternalConnectorModule } from '@jataqi/external-connectors';
import { GitHubExecutionModule } from '@jataqi/github-execution';
import { CopilotExecutionAdapterModule } from '@jataqi/copilot-execution-adapter';
import { AutonomousTestRepairModule } from '@jataqi/autonomous-test-repair';
import { AutonomousDeploymentModule } from '@jataqi/autonomous-deployment';
import { InfrastructureStateRegistryModule } from '@jataqi/infrastructure-state-registry';
import { PaymentsModule } from '@jataqi/payments';
import { BillingModule } from '@jataqi/billing';
import { RevenueLedgerModule } from '@jataqi/revenue-ledger';
import { UniversalVisibilityFabricModule } from '@jataqi/universal-visibility-fabric';
import { UniversalDistributionNervousSystemModule } from '@jataqi/universal-distribution-nervous-system';
import { ReconciliationModule } from '@jataqi/reconciliation';
import { CommercialAnalyticsModule } from '@jataqi/commercial-analytics';
import { CommercialIntelligenceModule } from '@jataqi/commercial-intelligence';
import { PortfolioGovernorModule } from '@jataqi/portfolio-governor';
import { CommercialMemoryModule } from '@jataqi/commercial-memory';
import { CommercialHealthModule } from '@jataqi/commercial-health';
import { CommercialObservabilityModule } from '@jataqi/commercial-observability';
import { CommercialEventStreamModule } from '@jataqi/commercial-event-stream';
import { CommercialCommandCenterModule } from '@jataqi/commercial-command-center';
import { AutonomousVentureFactoryModule } from '@jataqi/autonomous-venture-factory';
import { CognitiveKernelModule } from '@jataqi/cognitive-kernel';
import { MultiAgentCognitionModule } from '@jataqi/multi-agent-cognition';
import { MetaReasoningModule } from '@jataqi/meta-reasoning';
import { ProbabilisticEngineModule } from '@jataqi/probabilistic-engine';
import { HypothesisEngineModule } from '@jataqi/hypothesis-engine';
import { WorldModelModule } from '@jataqi/world-model';
import { CausalEngineModule } from '@jataqi/causal-engine';
import { TemporalEngineModule } from '@jataqi/temporal-engine';
import { OrbitalIntelligenceModule } from '@jataqi/orbital-intelligence';
import { ReproducibilityModule } from '@jataqi/reproducibility';
import { ResearchEvidenceModule } from '@jataqi/research-evidence';
import { HumanApprovalModule } from '@jataqi/human-approval';
import { RegulatoryGateModule } from '@jataqi/regulatory-gates';
import { PermanenceFabricModule } from '@jataqi/permanence-fabric';
import { CapabilityFabricModule } from '@jataqi/capability-fabric';
describe('createJataQi bootstrap', () => {
  it('boots the full stack and exposes all modules', async () => {
    const qi = await createJataQi();
    assert.equal(qi.kernel.isBooted(), true);
    assert.ok(qi.kernel.getModule<AgentRuntimeModule>('agent-runtime'));
    assert.ok(qi.kernel.getModule<KnowledgeService>('knowledge'));
    assert.ok(qi.kernel.getModule<KnowledgeGraphModule>('knowledge-graph'));
    assert.ok(qi.kernel.getModule<CommercialControlPlaneModule>('commercial-control-plane'));
    assert.ok(qi.kernel.getModule<AutonomousActionRuntimeModule>('autonomous-action-runtime'));
    assert.ok(qi.kernel.getModule<ExternalConnectorModule>('external-connectors'));
    assert.ok(qi.kernel.getModule<GitHubExecutionModule>('github-execution'));
    assert.ok(qi.kernel.getModule<CopilotExecutionAdapterModule>('copilot-execution-adapter'));
    assert.ok(qi.kernel.getModule<AutonomousTestRepairModule>('autonomous-test-repair'));
    assert.ok(qi.kernel.getModule<AutonomousDeploymentModule>('autonomous-deployment'));
    assert.ok(qi.kernel.getModule<InfrastructureStateRegistryModule>('infrastructure-state-registry'));
    assert.ok(qi.kernel.getModule<PaymentsModule>('payments'));
    assert.ok(qi.kernel.getModule<BillingModule>('billing'));
    assert.ok(qi.kernel.getModule<RevenueLedgerModule>('revenue-ledger'));
    assert.ok(qi.kernel.getModule<UniversalVisibilityFabricModule>('universal-visibility-fabric'));
    assert.ok(qi.kernel.getModule<UniversalDistributionNervousSystemModule>('universal-distribution-nervous-system'));
    assert.ok(qi.kernel.getModule<ReconciliationModule>('reconciliation'));
    assert.ok(qi.kernel.getModule<CommercialAnalyticsModule>('commercial-analytics'));
    assert.ok(qi.kernel.getModule<CommercialIntelligenceModule>('commercial-intelligence'));
    assert.ok(qi.kernel.getModule<AutonomousVentureFactoryModule>('autonomous-venture-factory'));
    assert.ok(qi.kernel.getModule<CognitiveKernelModule>('cognitive-kernel'));
    assert.ok(qi.kernel.getModule<MultiAgentCognitionModule>('multi-agent-cognition'));
    assert.ok(qi.kernel.getModule<MetaReasoningModule>('meta-reasoning'));
    assert.ok(qi.kernel.getModule<ProbabilisticEngineModule>('probabilistic-engine'));
    assert.ok(qi.kernel.getModule<HypothesisEngineModule>('hypothesis-engine'));
    assert.ok(qi.kernel.getModule<WorldModelModule>('world-model'));
    assert.ok(qi.kernel.getModule<CausalEngineModule>('causal-engine'));
    assert.ok(qi.kernel.getModule<TemporalEngineModule>('temporal-engine'));
    assert.ok(qi.kernel.getModule<OrbitalIntelligenceModule>('orbital-intelligence'));
    assert.ok(qi.kernel.getModule<ReproducibilityModule>('reproducibility'));
    assert.ok(qi.kernel.getModule<ResearchEvidenceModule>('research-evidence'));
    assert.ok(qi.kernel.getModule<HumanApprovalModule>('human-approval'));
    assert.ok(qi.kernel.getModule<RegulatoryGateModule>('regulatory-gates'));
    assert.ok(qi.kernel.getModule<PermanenceFabricModule>('permanence-fabric'));
    assert.ok(qi.kernel.getModule<CapabilityFabricModule>('capability-fabric'));
    assert.ok(qi.kernel.getModule<PortfolioGovernorModule>('portfolio-governor'));
    assert.ok(qi.kernel.getModule<CommercialMemoryModule>('commercial-memory'));
    assert.ok(qi.kernel.getModule<CommercialHealthModule>('commercial-health'));
    assert.ok(qi.kernel.getModule<CommercialObservabilityModule>('commercial-observability'));
    assert.ok(qi.kernel.getModule<CommercialEventStreamModule>('commercial-event-stream'));
    assert.ok(qi.kernel.getModule<CommercialCommandCenterModule>('commercial-command-center'));
    await qi.shutdown();
    assert.equal(qi.kernel.isBooted(), false);
  });

  it('runs a simple question against the default agent', async () => {
    const qi = await createJataQi();
    const agents = qi.kernel.getModule<AgentRuntimeModule>('agent-runtime');
    const res = await agents.run('hello world');
    assert.ok(res.answer.includes('hello world'));
    assert.equal(res.finishedReason, 'answer');
    await qi.shutdown();
  });

  it('ingests text, extracts entities, and retrieves', async () => {
    const qi = await createJataQi();
    const ks = qi.kernel.getModule<KnowledgeService>('knowledge');
    const g = qi.kernel.getModule<KnowledgeGraphModule>('knowledge-graph');
    const doc = await ks.ingestText('Alice founded Acme Corp. Bob works at Acme Corp.', { chunkSize: 500 });
    for (const cid of doc.chunkIds) {
      const c = await ks.getChunk(cid);
      if (c) {
        const r = g.extractFromText(c.text, { chunkId: cid, documentId: doc.id });
        for (const t of r.triples) g.linkMention(cid, t.object, 0.7, doc.id);
      }
    }
    const stats = g.stats();
    assert.ok(stats.entities >= 2, `expected entities, got ${stats.entities}`);
    assert.ok(stats.triples >= 1, `expected triples, got ${stats.triples}`);
    await qi.shutdown();
  });
});
